["^ ","~:resource-id",["~:shadow.build.npm/resource","node_modules/react-dom/lib/ReactErrorUtils.js"],"~:js","shadow$provide.module$node_modules$react_dom$lib$ReactErrorUtils=function(global,process,require,module,exports,shadow$shims){function invokeGuardedCallback(name,func,a){try{func(a)}catch(x){null===caughtError&&(caughtError=x)}}var caughtError=null;global={invokeGuardedCallback:invokeGuardedCallback,invokeGuardedCallbackWithCatch:invokeGuardedCallback,rethrowCaughtError:function(){if(caughtError){var error=caughtError;caughtError=null;throw error;}}};if(\"undefined\"!==typeof window&&\"function\"===typeof window.dispatchEvent&&\n\"undefined\"!==typeof document&&\"function\"===typeof document.createEvent){var fakeNode=document.createElement(\"react\");global.invokeGuardedCallback=function(name,func,a){func=func.bind(null,a);name=\"react-\"+name;fakeNode.addEventListener(name,func,!1);a=document.createEvent(\"Event\");a.initEvent(name,!1,!1);fakeNode.dispatchEvent(a);fakeNode.removeEventListener(name,func,!1)}}module.exports=global}","~:source","shadow$provide[\"module$node_modules$react_dom$lib$ReactErrorUtils\"] = function(global,process,require,module,exports,shadow$shims) {\n/**\n * Copyright 2013-present, Facebook, Inc.\n * All rights reserved.\n *\n * This source code is licensed under the BSD-style license found in the\n * LICENSE file in the root directory of this source tree. An additional grant\n * of patent rights can be found in the PATENTS file in the same directory.\n *\n * \n */\n\n'use strict';\n\nvar caughtError = null;\n\n/**\n * Call a function while guarding against errors that happens within it.\n *\n * @param {String} name of the guard to use for logging or debugging\n * @param {Function} func The function to invoke\n * @param {*} a First argument\n * @param {*} b Second argument\n */\nfunction invokeGuardedCallback(name, func, a) {\n  try {\n    func(a);\n  } catch (x) {\n    if (caughtError === null) {\n      caughtError = x;\n    }\n  }\n}\n\nvar ReactErrorUtils = {\n  invokeGuardedCallback: invokeGuardedCallback,\n\n  /**\n   * Invoked by ReactTestUtils.Simulate so that any errors thrown by the event\n   * handler are sure to be rethrown by rethrowCaughtError.\n   */\n  invokeGuardedCallbackWithCatch: invokeGuardedCallback,\n\n  /**\n   * During execution of guarded functions we will capture the first error which\n   * we will rethrow to be handled by the top level error handler.\n   */\n  rethrowCaughtError: function () {\n    if (caughtError) {\n      var error = caughtError;\n      caughtError = null;\n      throw error;\n    }\n  }\n};\n\nif (process.env.NODE_ENV !== 'production') {\n  /**\n   * To help development we can get better devtools integration by simulating a\n   * real browser event.\n   */\n  if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof document !== 'undefined' && typeof document.createEvent === 'function') {\n    var fakeNode = document.createElement('react');\n    ReactErrorUtils.invokeGuardedCallback = function (name, func, a) {\n      var boundFunc = func.bind(null, a);\n      var evtType = 'react-' + name;\n      fakeNode.addEventListener(evtType, boundFunc, false);\n      var evt = document.createEvent('Event');\n      // $FlowFixMe https://github.com/facebook/flow/issues/2336\n      evt.initEvent(evtType, false, false);\n      fakeNode.dispatchEvent(evt);\n      fakeNode.removeEventListener(evtType, boundFunc, false);\n    };\n  }\n}\n\nmodule.exports = ReactErrorUtils;\n};","~:removed-requires",["~#set",[]],"~:actual-requires",["^5",["~$shadow.js"]],"~:properties",["^5",["invokeGuardedCallback","rethrowCaughtError","invokeGuardedCallbackWithCatch"]],"~:compiled-at",1635270336805,"~:source-map-json","{\n\"version\":3,\n\"file\":\"module$node_modules$react_dom$lib$ReactErrorUtils.js\",\n\"lineCount\":2,\n\"mappings\":\"AAAAA,cAAA,kDAAA,CAAsE,QAAQ,CAACC,MAAD,CAAQC,OAAR,CAAgBC,OAAhB,CAAwBC,MAAxB,CAA+BC,OAA/B,CAAuCC,YAAvC,CAAqD,CAwBnIC,QAASA,sBAAqB,CAACC,IAAD,CAAOC,IAAP,CAAaC,CAAb,CAAgB,CAC5C,GAAI,CACFD,IAAA,CAAKC,CAAL,CADE,CAEF,MAAOC,CAAP,CAAU,CACU,IAApB,GAAIC,WAAJ,GACEA,WADF,CACgBD,CADhB,CADU,CAHgC,CAV9C,IAAIC,YAAc,IAoBdC,OAAAA,CAAkB,CACpBN,sBAAuBA,qBADH,CAOpBO,+BAAgCP,qBAPZ,CAapBQ,mBAAoBA,QAAS,EAAG,CAC9B,GAAIH,WAAJ,CAAiB,CACf,IAAII,MAAQJ,WACZA,YAAA,CAAc,IACd,MAAMI,MAAN,CAHe,CADa,CAbZ,CA2BpB,IAAsB,WAAtB,GAAI,MAAOC,OAAX,EAAqE,UAArE,GAAqC,MAAOA,OAAAC,cAA5C;AAAuG,WAAvG,GAAmF,MAAOC,SAA1F,EAAsJ,UAAtJ,GAAsH,MAAOA,SAAAC,YAA7H,CAAkK,CAChK,IAAIC,SAAWF,QAAAG,cAAA,CAAuB,OAAvB,CACfT,OAAAN,sBAAA,CAAwCgB,QAAS,CAACf,IAAD,CAAOC,IAAP,CAAaC,CAAb,CAAgB,CAC3Dc,IAAAA,CAAYf,IAAAgB,KAAA,CAAU,IAAV,CAAgBf,CAAhB,CACZgB,KAAAA,CAAU,QAAVA,CAAqBlB,IACzBa,SAAAM,iBAAA,CAA0BD,IAA1B,CAAmCF,IAAnC,CAA8C,CAAA,CAA9C,CACII,EAAAA,CAAMT,QAAAC,YAAA,CAAqB,OAArB,CAEVQ,EAAAC,UAAA,CAAcH,IAAd,CAAuB,CAAA,CAAvB,CAA8B,CAAA,CAA9B,CACAL,SAAAH,cAAA,CAAuBU,CAAvB,CACAP,SAAAS,oBAAA,CAA6BJ,IAA7B,CAAsCF,IAAtC,CAAiD,CAAA,CAAjD,CAR+D,CAF+F,CAepKpB,MAAAC,QAAA,CAAiBQ,MA5EkH;\",\n\"sources\":[\"node_modules/react-dom/lib/ReactErrorUtils.js\"],\n\"sourcesContent\":[\"shadow$provide[\\\"module$node_modules$react_dom$lib$ReactErrorUtils\\\"] = function(global,process,require,module,exports,shadow$shims) {\\n/**\\n * Copyright 2013-present, Facebook, Inc.\\n * All rights reserved.\\n *\\n * This source code is licensed under the BSD-style license found in the\\n * LICENSE file in the root directory of this source tree. An additional grant\\n * of patent rights can be found in the PATENTS file in the same directory.\\n *\\n * \\n */\\n\\n'use strict';\\n\\nvar caughtError = null;\\n\\n/**\\n * Call a function while guarding against errors that happens within it.\\n *\\n * @param {String} name of the guard to use for logging or debugging\\n * @param {Function} func The function to invoke\\n * @param {*} a First argument\\n * @param {*} b Second argument\\n */\\nfunction invokeGuardedCallback(name, func, a) {\\n  try {\\n    func(a);\\n  } catch (x) {\\n    if (caughtError === null) {\\n      caughtError = x;\\n    }\\n  }\\n}\\n\\nvar ReactErrorUtils = {\\n  invokeGuardedCallback: invokeGuardedCallback,\\n\\n  /**\\n   * Invoked by ReactTestUtils.Simulate so that any errors thrown by the event\\n   * handler are sure to be rethrown by rethrowCaughtError.\\n   */\\n  invokeGuardedCallbackWithCatch: invokeGuardedCallback,\\n\\n  /**\\n   * During execution of guarded functions we will capture the first error which\\n   * we will rethrow to be handled by the top level error handler.\\n   */\\n  rethrowCaughtError: function () {\\n    if (caughtError) {\\n      var error = caughtError;\\n      caughtError = null;\\n      throw error;\\n    }\\n  }\\n};\\n\\nif (process.env.NODE_ENV !== 'production') {\\n  /**\\n   * To help development we can get better devtools integration by simulating a\\n   * real browser event.\\n   */\\n  if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof document !== 'undefined' && typeof document.createEvent === 'function') {\\n    var fakeNode = document.createElement('react');\\n    ReactErrorUtils.invokeGuardedCallback = function (name, func, a) {\\n      var boundFunc = func.bind(null, a);\\n      var evtType = 'react-' + name;\\n      fakeNode.addEventListener(evtType, boundFunc, false);\\n      var evt = document.createEvent('Event');\\n      // $FlowFixMe https://github.com/facebook/flow/issues/2336\\n      evt.initEvent(evtType, false, false);\\n      fakeNode.dispatchEvent(evt);\\n      fakeNode.removeEventListener(evtType, boundFunc, false);\\n    };\\n  }\\n}\\n\\nmodule.exports = ReactErrorUtils;\\n};\"],\n\"names\":[\"shadow$provide\",\"global\",\"process\",\"require\",\"module\",\"exports\",\"shadow$shims\",\"invokeGuardedCallback\",\"name\",\"func\",\"a\",\"x\",\"caughtError\",\"ReactErrorUtils\",\"invokeGuardedCallbackWithCatch\",\"rethrowCaughtError\",\"error\",\"window\",\"dispatchEvent\",\"document\",\"createEvent\",\"fakeNode\",\"createElement\",\"ReactErrorUtils.invokeGuardedCallback\",\"boundFunc\",\"bind\",\"evtType\",\"addEventListener\",\"evt\",\"initEvent\",\"removeEventListener\"]\n}\n"]